default_platform(:ios)

KEY_ID      = "3WHS49Y787"
ISSUER_ID   = "17f51aa8-305f-48b3-acbe-fd8ed3dd5fb6"
KEY_PATH    = File.expand_path("~/private_keys/AuthKey_3WHS49Y787.p8")

platform :ios do
  desc "Upload metadata and screenshots to App Store Connect"
  desc "Submit already-uploaded build for review"
  lane :submit_for_review do
    api_key = app_store_connect_api_key(
      key_id: KEY_ID,
      issuer_id: ISSUER_ID,
      key_filepath: KEY_PATH,
      duration: 1200,
      in_house: false
    )

    deliver(
      api_key: api_key,
      app_version: "80.0",
      skip_binary_upload: true,
      submit_for_review: true,
      automatic_release: false,
      force: true,
      skip_screenshots: true,
      skip_metadata: true,
      run_precheck_before_submit: false,
      submission_information: {
        add_id_info_uses_idfa: false,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false
      }
    )
  end

  lane :upload_metadata do
    api_key = app_store_connect_api_key(
      key_id: KEY_ID,
      issuer_id: ISSUER_ID,
      key_filepath: KEY_PATH,
      duration: 1200,
      in_house: false
    )

    deliver(
      api_key: api_key,
      app_version: "80.0",
      skip_binary_upload: true,
      force: true,
      submit_for_review: false,
      automatic_release: false,
      overwrite_screenshots: true,
      screenshots_path: "./fastlane/screenshots",
      metadata_path: "./fastlane/metadata",
      run_precheck_before_submit: false
    )
  end
end
