steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/riddleverse-web/quiz-web-frontend:$COMMIT_SHA'
      - '.'
      - '-f'
      - 'Dockerfile'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - push
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/riddleverse-web/quiz-web-frontend:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - quiz-web-frontend
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/riddleverse-web/quiz-web-frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--quiet'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/riddleverse-web/quiz-web-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
